apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  server: "636cc488b8-faa56.cn-qingdao.nas.aliyuncs.com:/"
  driver: flexvolume
provisioner: alicloud/nas
reclaimPolicy: Delete
