mv JGCSHU.clt F_PT_ORG_KBRP_JGCSHU.clt
mv CFDGZJ.clt F_PT_ENT_KCFB_CFDGZJ.clt
mv CFDGJC.clt F_PT_ENT_KCFB_CFDGJC.clt
mv CFDGDZ.clt F_PT_ENT_KCFB_CFDGDZ.clt
mv CFDGDL.clt F_PT_ENT_KCFB_CFDGDL.clt
mv ZHXINX.clt F_AG_DP_KDPA_ZHXINX.clt
mv ZHBCXX.clt F_AG_DP_KDPA_ZHBCXX.clt
mv KEHUZH.clt F_AG_DP_KDPA_KEHUZH.clt
